server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: # 在此处配置 rabbitmq 的服务信息
        defaultRabbit: # 表示定义的名称，用于 binding 的整合
          type: rabbit # 消息组件类型
          environment: # 设置 rabbitmq 的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名字
          destination: studyExchange # 表示要使用的 Exchange 名称定义
          # 设置消息类型，本次为 json，文本则设置为“text/plain”
          content-type: application/json
          defaultbinder: defaultRabbit # 设置要绑定的消息服务具体设置

eureka:
  client:
    # 表示是否将自己注册进 EurekaServer 默认为 true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息，默认为 true，集群必须设置为 true 才能使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/  # 集群版配置
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 5
    instance-id: send-8001.com
    prefer-ip-address: true # 访问路径变为 ip 地址